@startwbs
<style>
node {
    MinimumWidth 160
    MaximumWidth 1600
    RoundCorner 8
}
</style>
+ Embedded Systems Engineering Road Map
 + Foundations
  + Mathematics
   + Linear Algebra
   + Calculus
   + Statistics
   + Discrete Mathematics
   + Numerical Analysis
  + Electrical Engineering
   + Electrical Circuits
  + Computer Science
   + Software Engineering
   + Operating Systems (OS)
   + A Programming Language
 + Soft Skills
  + Communication Skills
   + Verbal Communication
   + Written Communication
   + Presentation Skills
  + Problem Solving
   + Analysis
   + Emotional Intelligence
   + Resilience
   + Creativity
  + Critical Thinking
  + Teamwork
  + Being Self Driven
  + Adaptability
 + Embedded Systems
  + Microcontrollers
  + Programming Languages
   + C
   + C++
   + Python
   + Assembly
   + Rust
  + Real-Time OS
   + Zephyr
   + FreeRTOS
  + Embedded Linux OS
@endwbs