@startwbs Embedded Systemes Engineering Road Map
<style>
node {
    MinimumWidth 160
    MaximumWidth 1600
    RoundCorner 8
}
</style>
+ Embedded Systems Engineering Road Map
 + Foundations
  + Mathematics
   + Linear Algebra
   + Calculus
   + Statistics
   + Discrete Mathematics
   + Numerical Analysis
  + Computer Science
   + Computer Architecture
   + Operating Systems (OS)
   + Design Patterns
  + Electrical Engineering
   + Electrical Circuits
  + Software Engineering
   + General Programming
   + Version Control
   + Development Tools
 + Soft Skills
  + Communication Skills
   + Verbal Communication
   + Written Communication
   + Presentation Skills
  + Problem Solving
   + Analysis
   + Emotional Intelligence
   + Resilience
   + Creativity
  + Critical Thinking
  + Teamwork
  + Being Driven
   + Time Management
  + Adaptability
 + Embedded Systems
  + Microcontrollers
  + Systems Programming
   + C
   + C++
   + Python
   + Assembly
   + Rust
  + Real-Time OS
   + Zephyr
   + FreeRTOS
  + Embedded Linux OS
@endwbs