@startwbs Embedded Systemes Engineering Road Map
<style>
node {
    MinimumWidth 160
    MaximumWidth 1600
    RoundCorner 8
}
</style>
+ Embedded Systems Engineering Road Map
 + Engineering Foundations
  + Mathematics
   + Basic Mathematics
    + Algebra
    + Statistics
    + Trigonometry
   + Linear Algebra
   + Calculus
   + Statistics
   + Discrete Mathematics
   + Numerical Analysis
  + Computer Science
   + Computer Architecture
   + Operating Systems
   + Data Structures
   + Algorithms
   + Design Patterns
   + State Machines
   + Memory Managment
   + Cybersecurity
  + Electrical Engineering
   + Electrical Circuits
   + Electronic Fundamentals
   + Digital Design
   + Control Theory
   + Digital Signal Processing
   + EMC
  + Software Engineering
   + Programming
   + Version Control
   + CI/CD Pipelines
   + IDE
   + Documentation
   + Refactoring
   + SDLC Models
   + Compilers
   + Build Systems
   + Scripting
    + Python
    + Bash
   + Docker
 + Soft Skills
  + Learning
  + Communication
   + Articulate
   + Writing
    + Grammar
    + Style
   + Presentations
   + Relationships
  + Problem Solving
   + Analysis
   + Resilience
   + Creativity
  + Critical Thinking
  + Teamwork
   + Emotional Intelligence
  + Being Driven
   + Goal Setting
   + Motivation
   + Execution
   + Time Management
  + Adaptability
  + Project Management
  + Leadership
  + Career
 + Embedded Systems
  + Design Fundamentals
   + Logging
   + Bootloaders
   + Layered Architecture
   + Error Handling
  + Microcontrollers
   + Development Kits
   + Architectures
    + ARM
    + RISC-V
    + AVR
    + Xtensa
   + GPIO
   + ADC
   + DAC
   + Timer
   + PWM
   + Watchdog
   + Interrupt
   + DMA
   + Clock Management
   + Power Management
  + FPGAs
  + Sensors
  + Actuators
  + Prototyping
   + Breadbording
   + Soldering
  + PCB Design
   + CAD
  + Communication Protocols
   + Basic Serial
    + UART
    + I2C
    + SPI
   + High-Speed
    + Ethernet
    + USB
    + PCIe
   + Wireless
    + Bluetooth
    + Wi-Fi
    + LoRa
    + Zigbee
    + Thread
    + Matter
    + UWB
   + Network
   + Automotive
   + Industrial
   + Cellular
  + Systems Programming
   + C
   + C++
   + Python
   + Assembly
   + Rust
  + Debugging
   + GDB
   + JTAG
   + SWD
   + OpenOCD
  + Testing
   + Unit Test
   + Integration Test
   + Software In the Loop
    + Renode
    + Qmenu
   + Hardware In the Loop
   + Standards
  + Operating Systems
   + Real-Time
   + Embedded Linux
    + Linux Kernel
    + Device Drivers
    + U-Boot
    + Buildroot/Yocto
    + Threading
    + IPC
    + QT
  + Security
  + GUI
  + Test Equipment
   + Multimeter
   + Logic Analyzer
   + Oscilloscope
@endwbs